# Generated by Django 5.1.5 on 2025-01-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_artwork_art_artist_remove_comment_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
